// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezfwypxoyzmvdvftgjoe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6Znd5cHhveXptdmR2ZnRnam9lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTM3ODcsImV4cCI6MjA3MzY2OTc4N30.xY8SADqTrLWd3ttaD6VkV57XhKfVxofd6VRrOFeZJKs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});